//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfGoods.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeQuantityProduct
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public int IDTypeChange { get; set; }
        public string NumberDoc { get; set; }
        public double Quantity { get; set; }
        public System.DateTime DateChange { get; set; }
        public Nullable<int> IDUser { get; set; }
        public double StartQuantity { get; set; }
        public double InQuantity { get; set; }
        public double OutQuantity { get; set; }
        public string Note { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TypeChange TypeChange { get; set; }
        public virtual User User { get; set; }
    }
}
